### ISSUE TITLE
proposal: add a String() to do reverse enum lookup

### ISSUE THREAD

**Issue by rajatjindal** [ydnar/wasm-tools-go#127]
it would be nice to be able to do a reverse enum lookup and get string of error code based on the int value. 

how do you feel about adding something like below to the generated bindings:

```
type ErrorCode uint8

const (
	// Permission denied, similar to `EACCES` in POSIX.
	ErrorCodeAccess ErrorCode = iota

	// Resource unavailable, or operation would block, similar to `EAGAIN` and `EWOULDBLOCK`
	// in POSIX.
	ErrorCodeWouldBlock
)

func (e ErrorCode) String() string {
	return []string{
		"ErrorCodeAccess",
		"ErrorCodeWouldBlock",
	}[e]
}

```

**Comment by rajatjindal** [comment]
if this proposal looks reasonable, I would like to attempt to submit a PR for this. kindly let me know. thanks

**Comment by ydnar** [comment]
Good idea! Happy to review a PR. A couple points:

1. It should probably return the WIT string and not the Go string.
2. I'd prefer it avoid declaring a slice in the String method.
3. This could be useful for variant and flag types as well. 

Thanks!

**Comment by rajatjindal** [comment]
> I'd prefer it avoid declaring a slice in the String method.

having a slice outside the function is OK or you are suggesting some completely different way of doing this lookup?

**Comment by ydnar** [comment]
A fixed length array.
