### ISSUE TITLE
weird value printed when using function returning 

### ISSUE THREAD

**Issue by rajatjindal** [ydnar/wasm-tools-go#95]
Hello again,

I am trying to use wasm-tools-go to generate bindings for the following wit:

```
interface variables {
    /// Get an application variable value for the current component.
    ///
    /// The name must match one defined in in the component manifest.
    get: func(name: string) -> result<string, error>;

    /// The set of errors which may be raised by functions in this interface.
    variant error {
        /// The provided variable name is invalid.
        invalid-name(string),
        /// The provided variable is undefined.
        undefined(string),
        /// A variables provider specific error has occurred.
        provider(string),
        /// Some implementation-specific error has occurred.
        other(string),
    }
}
```

when using the bindings generated, I see weird value printed:

```
key: password, val is "\x00\x00\x00\x00\x00\x00"
```

pseudo code:

```
func Get(key string) (string, error) {
	result := variables.Get(key)
	if result.IsErr() {
		return "", errorVariantToError(*result.Err())
	}

	stdout.GetStdout().Write(cm.ToList([]byte(fmt.Sprintf("key: %s, val is %q \n", key, *result.OK()))))

	return *result.OK(), nil
}

```

I printed the value on host component implementation side, and it seems to be printing and returning the correct value. 

any pointers what could be wrong here? thank you so much for all the help so far.

**Comment by ydnar** [comment]
Hi there! Can you try with the latest version of wit-bindgen-go?

**Comment by rajatjindal** [comment]
Hi @ydnar, I tried this again today, and still running into same prob. I am adding  some more details incase if that helps narrow down the problem:


wit file:

```
interface variables {
    /// Get an application variable value for the current component.
    ///
    /// The name must match one defined in in the component manifest.
    get: func(name: string) -> result<string, error>;

    /// The set of errors which may be raised by functions in this interface.
    variant error {
        /// The provided variable name is invalid.
        invalid-name(string),
        /// The provided variable is undefined.
        undefined(string),
        /// A variables provider specific error has occurred.
        provider(string),
        /// Some implementation-specific error has occurred.
        other(string),
    }
}
```


generated code (ommitting error functions):

```
// Get represents the imported function "get".
//
// Get an application variable value for the current component.
//
// The name must match one defined in in the component manifest.
//
//	get: func(name: string) -> result<string, error>
//
//go:nosplit
func Get(name string) (result cm.ErrResult[string, Error]) {
	name0, name1 := cm.LowerString(name)
	wasmimport_Get((*uint8)(name0), (uint32)(name1), &result)
	return
}

//go:wasmimport fermyon:spin/variables@2.0.0 get
//go:noescape
func wasmimport_Get(name0 *uint8, name1 uint32, result *cm.ErrResult[string, Error])

```

When I print this inside host component:

```rust
tracing::trace!("variables get is {:?}", val);

## above prints:
# variables get is Ok("works2")
```

When I print this inside my guest code function:

```
func Get(key string) (string, error) {
	result := variables.Get(key)
	if result.IsErr() {
		return "", errorVariantToError(*result.Err())
	}

	val := result.OK()
	println(fmt.Sprintf("variables get inside sdk is %#v", *val))
	return *result.OK(), nil
}


func println(msg string) {
	stdout.GetStdout().Write(cm.ToList([]byte(msg)))
	stdout.GetStdout().Write(cm.ToList([]byte("\n")))
}

## above prints
# variables get inside sdk is \"\\x00\\x00\\x00\\x00\\x00\\x00\"
```

Thank you

**Comment by rajatjindal** [comment]
I realize my last comment is almost same as the original description. I will try to narrow down this to a small example, but if in the meantime you have any ideas that I could try, kindly let me know. thank you again.

**Comment by rajatjindal** [comment]
(kindly ignore me if this is incorrect)

do we need to lower/lift the string in the result here?

**Comment by ydnar** [comment]
Call OK() on the result to extract the string.

**Comment by rajatjindal** [comment]
I did call `.OK()` on the result (added partial code below in comment below), but still get same value

```
val := result.OK()
println(fmt.Sprintf("variables get inside sdk is %#v", *val))
```

**Comment by ydnar** [comment]
Can you use %s? Val should be *string.

**Comment by rajatjindal** [comment]
Hi Randy, thank you for your continued feedback on this. I tried this as well, and see following:

```
variables get inside sdk is \0\0\0\0\0\0\0
```

I should mention that the number of `\0` here (or `\x00` that I mentioned earlier) is exactly the same as number of characters that I am expecting as output. It seems like its just the content which is not correct.

**Comment by ydnar** [comment]
1. Have you successfully been able to have an imported function return a `string`?
2. Is the length of the returned `string` correct (7 bytes)? It’s just returning blank memory?
3. Can you check the value of the `unsafe.StringData` pointer of the returned string?
4. What implements the `get()` function?

**Comment by rajatjindal** [comment]
Hi Randy,

I just tried this with a host-component that implements following wit:

```
    /// Return a list of all the keys in kv store
    get-keys: func() -> result<list<string>, error>;
```

and the result I receive back is (the number of items are same as the unique keys available in the kv store):

```
[]string{"", ""}
```

These host components that I am trying out are implemented as part of [fermyon/spin](github.com/fermyon/spin)

e.g. [variables](https://github.com/fermyon/spin/blob/7833e71ab04decd0075b47593ee1b2b841b5f826/crates/variables/src/host_component.rs#L80)

and 

[kv store](https://github.com/fermyon/spin/blob/7833e71ab04decd0075b47593ee1b2b841b5f826/crates/key-value-sqlite/src/lib.rs#L131)

**Comment by rajatjindal** [comment]
I will be trying out the other suggestions and will report back the result 👍

**Comment by rajatjindal** [comment]
on trying to print stringdata, I get following:

```
stringdata is (*uint8)(0x20)
```

^^ is the output of following code:

```
// Get an application variable value for the current component.
//
// The name must match one defined in in the component manifest.
func Get(key string) (string, error) {
	result := variables.Get(key)
	if result.IsErr() {
		return "", errorVariantToError(*result.Err())
	}

	val := result.OK()

	//check the value of the unsafe.StringData pointer of the returned string
	stringdata := unsafe.StringData(*val)

	stdout.GetStdout().Write(cm.ToList([]byte(fmt.Sprintf("stringdata is %#v \n", stringdata))))
	return *result.OK(), nil
}

```

**Comment by rajatjindal** [comment]
I have also created a small repro repo for this: https://github.com/rajatjindal/wasip2-string

it needs to run using `spin` (I can try to get a reproducible scenario with `wasmtime` if you think that would be better).

**Comment by ydnar** [comment]
Thanks. I assume this is run with the wasip2 fork of TinyGo?

**Comment by rajatjindal** [comment]
yes, that is right. I updated the repo in last day or so.

**Comment by ydnar** [comment]
> I have also created a small repro repo for this: https://github.com/rajatjindal/wasip2-string
> 
> 
> 
> it needs to run using `spin` (I can try to get a reproducible scenario with `wasmtime` if you think that would be better).

Possible to do one that works with `wasmtime`? Just to rule out the additional software?

**Comment by rajatjindal** [comment]
Hi Randy, I am trying to reproduce the issue with wasmtime, but unable to do so far.

The repo is here: https://github.com/rajatjindal/wasip2-string-wasmtime

this uses `environment` host component, but this returns the string correctly as expected. 

I am trying to narrow down to a testcase that we can verify with both.

**Comment by ydnar** [comment]
Does environment work in spin?

**Comment by rajatjindal** [comment]
i was able to reproduce this issue with wasmtime. I've updated the repo with the scenario: https://github.com/rajatjindal/wasip2-string-wasmtime

need to use a fork that implements additional functions in environment host to demonstrate the problem.

**Comment by rajatjindal** [comment]
this is a repo I created for running similar code using `rust`:

https://github.com/rajatjindal/wasip2-string-rust

I hope this helps

**Comment by ydnar** [comment]
Thanks for the reproduction repos, they’ve been a ton of help.

I’ve verified that the host successfully passes the string in the `result<string, error>`. The issue seems to be when the generated function returns `ErrResult[string, Error]` by value on the stack.

It seems to be mangled. If I make it store the `data` field as a byte slice, it works. 

More work tomorrow.

**Comment by rajatjindal** [comment]
if its of any help, the bindings in the rust repo I shared has useful info on how that lifting is done there. (I found it useful as I am not very familiar with canonical abi spec as such)

**Comment by ydnar** [comment]
Give https://github.com/ydnar/wasm-tools-go/pull/121 a shot!

**Comment by rajatjindal** [comment]
YES IT WORKS :)

**Comment by ydnar** [comment]
One thing I noticed debugging this: Spin doesn't support blocking write and flush, so panic, print, and println do not work. Nor does fmt.Print*.

This seems like an obvious addition to the Spin API surface, particularly for debugging.
